#!/usr/bin/env bash
#
# Generate colors.sh from the current macOS desktop wallpaper.
#   utils/generate_theme.sh [--reload]
#
# Picks a dark background tone + a vibrant accent from the wallpaper's palette
# and writes them to colors.sh (backing up the previous file first).

set -euo pipefail
CONFIG_DIR="${CONFIG_DIR:-$HOME/.config/sketchybar}"

# 1. Locate the current wallpaper.
WALL="$(osascript -e 'tell application "System Events" to get picture of current desktop')"
[ -f "$WALL" ] || { echo "Wallpaper not found: $WALL" >&2; exit 1; }
echo "Wallpaper: $WALL"

# 2. Normalize to a small PNG (handles HEIC/JPEG/etc.) so PIL can read it.
TMP="$(mktemp -t sb_wall).png"
trap 'rm -f "$TMP"' EXIT
sips -s format png -Z 400 "$WALL" --out "$TMP" >/dev/null 2>&1

# 3. Back up the existing palette.
[ -f "$CONFIG_DIR/colors.sh" ] && cp "$CONFIG_DIR/colors.sh" "$CONFIG_DIR/colors.sh.bak"

# 4. Extract palette + derive the theme.
python3 - "$TMP" "$CONFIG_DIR/colors.sh" "$WALL" <<'PY'
import sys, colorsys
from PIL import Image

src, out, wall = sys.argv[1], sys.argv[2], sys.argv[3]

img = Image.open(src).convert("RGB").resize((200, 200))
q = img.quantize(colors=16)            # median-cut palette
pal = q.getpalette()
swatches = [(cnt, tuple(pal[i*3:i*3+3])) for cnt, i in q.getcolors()]
swatches.sort(reverse=True)            # most frequent first

def hsv(c):
    r, g, b = [x / 255 for x in c]
    return colorsys.rgb_to_hsv(r, g, b)

def adjust(c, v=None, s=None):
    h, ss, vv = hsv(c)
    if v is not None: vv = v
    if s is not None: ss = s
    r, g, b = colorsys.hsv_to_rgb(h, ss, vv)
    return (int(r*255), int(g*255), int(b*255))

def hexc(c, a=0xff):
    return "0x%02x%02x%02x%02x" % (a, c[0], c[1], c[2])

# Dominant tone drives the dark background shades.
dominant = swatches[0][1]
dom_sat = min(hsv(dominant)[1], 0.55)
bar   = adjust(dominant, v=0.10, s=dom_sat)  # bar background (very dark)
item  = adjust(dominant, v=0.24, s=dom_sat)  # item background (a touch lighter)
hover = adjust(dominant, v=0.34, s=dom_sat)  # hover highlight (lighter still)

# Accent = the most "vibrant" swatch (saturation * brightness), boosted.
accent = max((c for _, c in swatches), key=lambda c: hsv(c)[1] * hsv(c)[2])
ah, as_, av = hsv(accent)
accent = adjust(accent, v=max(av, 0.85), s=max(as_, 0.6))

with open(out, "w") as f:
    f.write("#!/bin/bash\n\n")
    f.write("# Auto-generated by utils/generate_theme.sh from:\n")
    f.write("#   %s\n\n" % wall)
    f.write("export WHITE=0xffffffff\n\n")
    f.write("export BAR_COLOR=%s\n" % hexc(bar))
    f.write("export ITEM_BG_COLOR=%s\n" % hexc(item))
    f.write("export HOVER_COLOR=%s\n" % hexc(hover))
    f.write("export ACCENT_COLOR=%s\n" % hexc(accent))
    f.write("export RED=0xfff38ba8\n")

print("  BAR_COLOR     = %s" % hexc(bar))
print("  ITEM_BG_COLOR = %s" % hexc(item))
print("  ACCENT_COLOR  = %s" % hexc(accent))
PY

echo "Wrote $CONFIG_DIR/colors.sh (backup: colors.sh.bak)"

if [ "${1:-}" = "--reload" ]; then
  sketchybar --reload && echo "Reloaded SketchyBar"
fi
