repoPaths:
  schibsted-smb/frontend-monorepo: ~/work/mittanbud/front/frontend-monorepo

prSections:
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: My Pull Requests
    filters: is:open author:@me

keybindings:
  prs:
    - key: W
      name: work on PR in Herdr
      command: ~/.local/bin/herdr-pr work "{{.RepoPath}}" "{{.PrNumber}}"
    - key: R
      name: review PR in Herdr
      command: ~/.local/bin/herdr-pr review "{{.RepoPath}}" "{{.PrNumber}}"
