# ─── Prefix ───────────────────────────────────────────────────────────────────
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# ─── Reload ───────────────────────────────────────────────────────────────────
bind r source-file ~/.config/tmux/tmux.conf

# ─── Splits ───────────────────────────────────────────────────────────────────
unbind %
bind | split-window -h

unbind '"'
bind - split-window -v

# ─── Resize ───────────────────────────────────────────────────────────────────
bind -r C-j resize-pane -D 5
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5
bind -r C-h resize-pane -L 5

# ─── Zoom ─────────────────────────────────────────────────────────────────────
bind -r m resize-pane -Z

# ─── Sessions ─────────────────────────────────────────────────────────────────
bind X command-prompt -p "Command:" "new-session -s '%1' '%1'"

# ─── Misc ─────────────────────────────────────────────────────────────────────
bind C-l send-keys C-l

# ─── Vi copy mode ─────────────────────────────────────────────────────────────
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
unbind -T copy-mode-vi MouseDragEnd1Pane
