# ─── Terminal ─────────────────────────────────────────────────────────────────
set -g default-terminal "tmux-256color"
set -gq allow-passthrough on
set -g extended-keys always
set -g extended-keys-format csi-u
set -ga terminal-features "*:extkeys"

# ─── Session ──────────────────────────────────────────────────────────────────
set -g detach-on-destroy off
set -g base-index 1
set -g renumber-windows on

# ─── Input ────────────────────────────────────────────────────────────────────
setw -g mode-keys vi
set-window-option -g mode-keys vi
set -g mouse on

# ─── Status bar ───────────────────────────────────────────────────────────────
set -g status-position bottom
